# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

latex: false
fortran: false

matrix:
  include:
    - dist: xenial
      r_packages:
        - knitr
        - rmarkdown
        - ggplot2
        - devoid
        - bench
        - rlang
        - tidyr
        - ggridges
        - hexbin
        - dplyr
        - sessioninfo
        - magick
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - dist: xenial
      r: 3.3
      r_packages:
        - knitr
        - rmarkdown
        - ggplot2
        - devoid
        - bench
        - rlang
        - tidyr
        - ggridges
        - hexbin
        - dplyr
        - sessioninfo
        - magick
    - os: osx
      brew_packages:
        - freetype
        - libpng
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - gsfonts
      
