// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// agg_dev
SEXP agg_dev(String file, int width, int height, double pointsize, SEXP bg);
RcppExport SEXP _ragg_agg_dev(SEXP fileSEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP pointsizeSEXP, SEXP bgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type file(fileSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< double >::type pointsize(pointsizeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bg(bgSEXP);
    rcpp_result_gen = Rcpp::wrap(agg_dev(file, width, height, pointsize, bg));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
void rcpp_hello_world();
RcppExport SEXP _ragg_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_hello_world();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ragg_agg_dev", (DL_FUNC) &_ragg_agg_dev, 5},
    {"_ragg_rcpp_hello_world", (DL_FUNC) &_ragg_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ragg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
