# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

agg_dev <- function(file, width, height, pointsize, bg) {
    .Call(`_ragg_agg_dev`, file, width, height, pointsize, bg)
}

rcpp_hello_world <- function() {
    invisible(.Call(`_ragg_rcpp_hello_world`))
}

